name: CI

on:
  push:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: jdx/mise-action@v2
        with:
          install: true
      - run: mise run check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: jdx/mise-action@v2
        with:
          install: true
      - run: cargo test --all-features

  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: jdx/mise-action@v2
        with:
          install: true
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: jdx/mise-action@v2
        with:
          install: true
      - run: cargo clippy --all-targets --all-features -- -D warnings

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: jdx/mise-action@v2
        with:
          install: true
      - uses: rustsec/audit-check@v1
        with:
          token: ${{ github.token }}
